### ISSUE TITLE
How we will manage carrying user data throughout the website?

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#13]
So the way we're setup is a static page-by-page format. If a user navigates to the next page, it will be a page on its own, data will not carry through, like the user's login status. To keep a user logged in, we would need to design it as a single page web app, which [this article](http://tutorialzine.com/2015/02/single-page-app-without-a-framework/) can probably help us with (haven't exactly looked at it thoroughly yet, but I did skim it a bit -- the basis of the article seems to match our current format: jQuery/Handlebars, and pages are separated by an encapsulation div with class '.page' - if it doesn't make sense here, the article should take care of that understanding ^^). Article also covers hashing, which should allow browser history to function normally.

I think it might get pretty messy as we add the features that we need, but it should be fine (to keep things clean/organized, each page can be a handlebars template, loaded into the single index page, hopefully that'll work well).

Thoughts on this? Other solutions?

**Comment by lburkett** [comment]
So a multi-page web application could handle user logins with session variables. However, we should meet with Carla to get the final say.
