### ISSUE TITLE
Overview Page Temporary Data

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#14]
Populate the overview page with filler data (same JSON object from details).

**Comment by allenduy** [comment]
~~Currently working on this, so to avoid merge conflicts, I'll be working in overview.html and possibly some other files, but that one for sure.~~

**Comment by lburkett** [comment]
Should bring this up with Carla to determine what a user should and shouldn't be able to see on the overview.

**Comment by allenduy** [comment]
Seeing how the overview seems a bit empty, any ideas on what might seems good to show?

I was thinking something like a "last/latest activity" kind of thing with either date+time and/or the activity. I think it would be useful to them to know that their grant process is getting attention (think that was one of her intentions for this application). Thoughts? Ideas?
