### ISSUE TITLE
Footer size

### ISSUE THREAD

**Issue by MorganNesbitt** [ASUKanbosalCapstone/Kanbosal#2]
# Footer takes up large portion of screen now.

![image](https://cloud.githubusercontent.com/assets/5340765/11425754/6a8de27c-9414-11e5-9d43-0d65016ae73c.png)

**Comment by allenduy** [comment]
Sorry about that, I set the footer size to a fixed height to make the footer positioning work. My latest push should look better. (Although it does keep the slightly larger fixed height)
