### ISSUE TITLE
Account Preferences

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#22]
Create a page for users to update ~~profile information (unless the profile info is retrieved from their gmail/ASU profile)~~ preferences.

**Comment by MorganNesbitt** [comment]
All profile info should be retrieved by google. When a user needs to sign up they need to sign up for a respective gmail account (or business account which uses gmail). We should only handle info related to when they sign up to our service (pi, vs researcher, etc). Presumably which should not be able to be changed upon signing up

**Comment by allenduy** [comment]
Ah, so I'll just have it set up for changing user preferences. (not profile info)
