### ISSUE TITLE
Switching from tinymce to markdown.

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#28]
#### Situation

Currently we have tinymce implemented for editing the card notes. However, there are limits to what we can store in our database. ~~To make our lives simpler, we were thinking of using another solution.~~ Either way will require sanitizing the string (or simply changing to unicode escape symbols)
#### Solution

Found [this bootstrap plugin](http://www.codingdrama.com/bootstrap-markdown/) or [this](http://samwillis.co.uk/pagedown-bootstrap/demo/browser/demo.html) or [this](http://summernote.org/) (all just quick finds, compatible with bootstrap). Thoughts?

Personally find preference towards the first (bootstrap markdown) or last one (summernote). The first one, although it looks really clean, doesn't function so smoothly, which you can probably see for yourself on our live ec2 site.

[edit] Right now, you can see tinymce used in the details page, or the bootstrap plugin for markdown on the overview page.

**Comment by lburkett** [comment]
Let's plan on using tinymce for now, but we can approach this topic again if we run in to any road blocks in the future.

**Comment by lburkett** [comment]
Currently using summernote now to handle all text editor like functions as it allows for a bit more customization and looks pretty good out of the box.
