### ISSUE TITLE
Lock a sortable card.

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#31]
This is to be implemented in the future (since we can't do it yet); just leaving it here for next time.
#### Problem

When a card is moved to the complete column, it must be confirmed/cleared by a PI to have it visible in the next stage. The card must be locked in that column to prevent further changes to the card. If the card is rejected (is this a thing?) by the next stage, we must unlock it in the previous stage, and move the card back to in progress, giving it some sort of label for the case.
#### Solution

Using the features that come with the JQueryUI cards, lock the card upon confirmation. To make the check, we can't simply mark the card as locked, since it would still need to be unlocked in the next stages  (**we can store an array of booleans to the card with indexes that correspond to the stages; discuss this below**). Same goes for rejection of a card.

[edit]
#### Resources

So looking at the  JQuery UI Sortable [docs](http://api.jqueryui.com/sortable/), we can use the following option: (in sortable.js)

```
$( ".selector" ).sortable({
  cancel: ".unsortable"
});
```

This will let us apply the class `.unsortable` to whichever card has a lock value of true, in their corresponding stage using either of the jquery methods: `.addClass()` or `toggleClass()`, or go into detaiBoard.html and conditionally (using handlebars) add the class only to the complete column.

**Comment by lburkett** [comment]
Do we need multiple locks for the card? Couldn't we just use a single boolean lock and then change it as it moves through the different boards?

**Comment by allenduy** [comment]
Let me know if anything!
