### ISSUE TITLE
Database format validation.

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#34]
I guess this issue can be used as a discussion on where we want to do the database validation. The big question is if we want to do the validation client-side, server-side, or some mix of both.

At the moment I have some bare-bones validation for cards setup in the web service here [kanbosalService/collectionDriver.js](https://github.com/ASUKanbosalCapstone/Kanbosal/blob/database-implementation/kanbosalService/collectionDriver.js) that looks like such:

``` javascript
var ensureCardFormat = function(doc, errorCallback) {
    if (!doc.title instanceof String)
        errorCallback(new Error("title must be a string."));
    doc.notes.forEach(function(note) {
        if (!note instanceof String)
            errorCallback(new Error("notes must be strings."));
    });
    if (!doc.documentUrl instanceof String)
        errorCallback(new Error("documentUrl must be a string."));
    if (!doc.timeCreated instanceof Object)
        errorCallback(new Error("timeCreated must be an object of Date."));
    if (!doc.timeLastEdit instanceof Object)
        errorCallback(new Error("timeLastEdit must be an object of Date."));
    if (!doc.status instanceof String)
        errorCallback(new Error("status must be a string."));
    doc.tags.forEach(function(tag) {
        if (!tag instanceof String)
            errorCallback(new Error("tags must be strings."));
    });
    doc.userIds.forEach(function(userId) {
        if (!userId instanceof String)
            errorCallback(new Error("userIds must be ObjectIDs."));
    });
    doc.lock.forEach(function(l) {
        if (!l instanceof Boolean)
            errorCallback(new Error("locks must be booleans."));
    })
}
```

Pretty ugly, but it must be done to ensure proper document delivery.

I think we should extend this to the other collections and if the format is incorrect we can just have the service respond back with an error or bad request. Another question would be, how would our application handle receiving an error in the off chance it does happen?

**Comment by allenduy** [comment]
So we should be able to do form validation to check their input as they enter their inputs to the form. As for the dates, the auto-generation would be out of the hands of the user, and in that case would mean the request will never work, requiring a developer to correct that problem.

**Comment by lburkett** [comment]
Yes, the dates are not necessary to validate. I had them in there to originally cover my bases, but they are generated with Date objects.

Is form validation going to be enough do you think? I guess the worry was someone being able to make a request to the service in some unknown way and that's why I started implementing server side checks.

**Comment by allenduy** [comment]
Ahh, that makes sense. Since it's using RESTful service, anyone can enter anything into the uri themselves.

**Comment by allenduy** [comment]
Actually, that may be preventable if the requests are done only by the server, if i'm thinking of it correctly (i can limit access to the port belonging to mongo to specific IP)

**Comment by lburkett** [comment]
Yeah, right now it should be limited only to requests from localhost on port 3000. Shouldn't need to make any adjustments.

**Comment by lburkett** [comment]
Was just worried about potential ways to circumvent it by forging a request in our app or something. Might be completely unnecessary.

**Comment by lburkett** [comment]
So this can be resolved by attaching the middleware function `authenticate` to all our endpoints once the application is finished. This ensures that a session is active before being able to make any request to the server. This doesn't resolve all the issues with it, but at least will keep outside users from being able to interact with the service.
