### ISSUE TITLE
Updating queries.

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#37]
Need to insert the correct updating queries for both the grants and cards. These collections should be updated when a card is updated, moved, etc.

**Comment by RBenW** [comment]
https://docs.mongodb.org/manual/reference/method/db.collection.update/

**Comment by lburkett** [comment]
I will look into replacing our insert and update requests an upsert instead to cut down on the complexity of the service. As for now you can just use them individually and if/when it changes it will just be a simple line fix in the RESTful call.

**Comment by lburkett** [comment]
After looking into implementing upsert, I found that it won't do what we want it to do. I am closing this issue to remake individual issues regarding updating elements.
