### ISSUE TITLE
Overview Board Sidebar Change/Removal

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#4]
Currently unnecessary display for list of grants, as the overview board already has them listed.

What we want: either remove the sidebar all together, or change it so that it is of more use.

**Comment by MorganNesbitt** [comment]
## Situation
- Removing making sense to me, but it may confuse the user.

## Possible solution
- If removing confuses the user, than I would suggest, potentially making the sidebar categorized like I had in my original designs.

**Comment by lburkett** [comment]
Remove the sidebar from the overview and keep the sidebar for the detail view for quick navigation.
