### ISSUE TITLE
Get requests for Cards

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#40]
Call the corresponding get request to retrieve all the cards in the collection belonging to the passed grant.

Should be an ajax call in the handlebars file corresponding to populating the cards in detail.html. After the call, iterate through the return object to display all the cards following the template.

This might end up being a few queries to get the grants belonging to the corresponding columns.

**Comment by mjyi2** [comment]
Are the cards in each column for the detail board going to be stored as a separate grant object in the database? Or is it being stored in the format that we currently have in the json folder (cards.json)? If it is the later, then would I still need to do multiple queries?

**Comment by lburkett** [comment]
So the query you will want is at "localhost:3000/grants/:id/:userPerm/cards". You give it a grantId and the user permissions index that lines up with the stage to query for (e.i. 0 for Research, 1 for Internal, 2 for ASU, or 3 for Complete). That will return the list of cards for the grant at the correct stage and from there you can sort the cards with their "status" attribute.

If it is easier, I can make that same query return 3 collections of cards that correspond to the columns. Whichever is easiest for you to work with.

**Comment by mjyi2** [comment]
Oh okay gotcha

**Comment by lburkett** [comment]
I think returning the 3 collections will be the cleaner way to do this and removes another dependency on two fields being the same in our database schema. This way the grant object dictates exactly what cards belong to it and where those cards lie within the grant.

I will have up the changes soon and you can pull from my branch to grab them. The endpoint will still be _"localhost:3000/grants/:id/:userPerm/cards"_, but it will return three collections of cards instead of one giant collection.

**Comment by mjyi2** [comment]
Okay sounds good
