### ISSUE TITLE
PI page when clicking on a specific grant on overview board

### ISSUE THREAD

**Issue by mjyi2** [ASUKanbosalCapstone/Kanbosal#5]
So for regular users, they will see the specific board they belong to (Research, ASU, or Internal). What would the PI be directed to?

Possible solutions:
 1.) Pop-up with the sub-board links
 2.) Have a collapsible list under the grant name in the overview board with sub-board links
 3.) Have the columns be links to their respective board 

I assume for any change/implementation, we would need to adjust the normal user's overview page as well.

**Comment by allenduy** [comment]
I think all users are taken to the overview board to begin with, then PI will see which items are marked as complete (in their respective column of research/ASU/internal), and has final say on whether it can be moved to the next column (research -> internal or internal -> ASU). Once moved, it will be listed in the To Do column of the next section, and won't show complete, now it would be listed as 'under review'.

Edit: Basically an admin version of the overview board, or something like that.

**Comment by mjyi2** [comment]
Oh okay forgot we're listing all of the items on the overview board

**Comment by lburkett** [comment]
Add conditionals to certain view objects on the board for when a PI is viewing it. They should own the grants and be able to "Create", "Complete", and "Remove" grants.

**Comment by allenduy** [comment]
Followup question -- is there a different PI assigned to each individual grant (multiple PIs managing several grants), or are there multiple PIs managing all grants, or not very many, possibly only one, PI managing as the admin?

**Comment by lburkett** [comment]
Added this question to our questions to ask Carla.
