### ISSUE TITLE
Update sidebar with user's grants

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#53]
Should be very similar to what is being done in the overview, but will need to be done on both the overview and detail page to get the grants the user can see. Should just be a simple request to "/getOverview" then use that data to populate the sidebar. In [overviewGrants.js](https://github.com/ASUKanbosalCapstone/Kanbosal/blob/master/client/javascript/overviewGrants.js), "/getOverview" is already called so the sidebar can just be added in the success function after it populates the overviewPanel template.

**Comment by allenduy** [comment]
I believe this was implemented and merged. Re-open issue if needed.
