### ISSUE TITLE
Create New Card

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#6]
#### Situation

On the index page, we can click on the button to create a new card, but that is a very simple, general feature implementation.
#### Solution

We want users to have the ability to add a card with specified inputs and options, which would then add the item to the To Do column. For now, only researchers should have the option to add a new card.

A possible reason why other user types would need to create a new card, is if they want to add an additional requirement, which has not been discussed.

**Comment by lburkett** [comment]
See issue #39.

If the card created always ends up in the To Do column of the Research table, then it has been implemented in [features/sessions](https://github.com/ASUKanbosalCapstone/Kanbosal/tree/features/sessions) branch.
