### ISSUE TITLE
Moving card from the complete column to the next table

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#67]
There is no way for a card to move to the next table when it is in the complete column. How this exactly is implemented is still up for debate a bit. I was thinking maybe a check mark that appears on the card when it is in the complete column that allows the card to be moved to the next table. This is a check mark that would ultimately be hidden from view for a normal user.

Another easier option might be to have a separate page that only admins can access that displays the cards in the complete column ready to be moved to the next column.

Of course these are only thoughts and we can discuss how we think this should be implemented here.

**Comment by MorganNesbitt** [comment]
You think we need to separate it by grants, or just pour all the cards into the columns and allow them to be moved around?

**Comment by lburkett** [comment]
It would probably be best to separate it by grants and let them approve them from there. Maybe just a simple display with the 4 columns corresponding to research, internal, asu, complete and it pulls only the complete column cards. From there they can just hit a check mark next to it and it will move to the next table?

Though at that point it's starting to sound more like just the normal table views. Maybe having admin only controls on the tables we already have to approve the complete items is the best bet.

**Comment by MorganNesbitt** [comment]
so another admin page than?

**Comment by lburkett** [comment]
I think either would work. I'm having trouble envisioning exactly how the admin page would work without adding a whole other directory for admins.

I think I would be leaning more towards just having it integrated on the detail page for each table.

**Comment by MorganNesbitt** [comment]
wait i'm confused about the detail page. is the detail page different for admins?

**Comment by lburkett** [comment]
Well it should look the same for them. I just meant that admins would have controls on the detail page that would allow them to confirm the completed cards.

**Comment by MorganNesbitt** [comment]
Oh like confirm buttons to move to the next column? What about reject to move to the previous?

**Comment by lburkett** [comment]
I think they would just drag it back to in progress.

**Comment by MorganNesbitt** [comment]
no like from internal to research or something.

**Comment by lburkett** [comment]
I'm not sure that would be necessary as only the PI would be able to move it forward.

**Comment by MorganNesbitt** [comment]
Right but didn't she talk at some point about being able to move it backwards to other columns. Like the big department columns.

**Comment by lburkett** [comment]
I know we talked about the other tables not needing to create new cards. I'm not remembering what she was saying about that. I guess it wouldn't hurt, but I'm not sure how we would add both to a table. Perhaps doing a separate view purely for the PI is a better idea.
