### ISSUE TITLE
Sidebar Content

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#7]
#### Situation

The current sidebar displays a list of demo grants, using the following code:

```
// add into div#content
<div id="sidebar" class="toggled"></div>
<div id="menu-toggle" class="glyphicon glyphicon-menu-right large"></div>
<div id="contentview" class="container-fluid toggled">
    {{ main content }}
</div>

// add to include JS section
<script src="javascript/sidebar.js"></script>
```
#### Solution

If we decided against keeping the top navbar, we would include user info and options on the sidebar, and play with the styles. Otherwise, we can add another issue regarding navbar templates.

**Comment by lburkett** [comment]
So removing the grants from the navbar entirely should be done. We will reserve the middle space for context sensitive buttons determined by the page. Refer to the detail view page for the navbar setup.

Add a drop down menu for the user with "My Account" and "Sign Out" options for them to select.
