### ISSUE TITLE
Determine current department

### ISSUE THREAD

**Issue by MorganNesbitt** [ASUKanbosalCapstone/Kanbosal#73]
Currently there is no way to determine what department you currently are on purely from the detail page.

This might prove confusing if you are an admin, trying to remember what page you are on.

**Comment by lburkett** [comment]
The stage can be found in the user object's `user.permissions.stage` defined in line 95 of detail.js. The index returned can be directly associated with the table being viewed. Stage 0 = Research table, Stage 1 = Internal, and Stage 2 = ASU.

**Comment by MorganNesbitt** [comment]
No. Like visually displayed on the page. So the PI can know

**Comment by lburkett** [comment]
I mean that's how you could figure out what stage you are in to display the real name of the table. If stage 0 display Research, etc.

**Comment by MorganNesbitt** [comment]
Ah. Naturally

**Comment by allenduy** [comment]
It might also be useful to know which grant they are looking at, since we currently have it where they either know which they've clicked on, or examine the contents.
