### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#8]
#### Situation

Currently, no login system has been implemented just yet.
#### Solution

For this issue, we will not yet need to have the login account combined with the saved data. Just have the ability to register and login. User specific data system will be a future issue. (... if any of that made sense, yay!)

Currently, we are looking at using ~~[Auth0](https://auth0.com/docs/quickstart/spa/jquery/no-api)~~ OAuth2, and find out whether there is the possibility of getting administrator approval for security. If this option is unavailable, we may have to look for another solution or implement our own.
##### Admin Approval Solution

When a new user creates an account, we will flag their user in the database as unconfirmed until someone internal can approve this user.

**Comment by MorganNesbitt** [comment]
Solved with google authentication
