### ISSUE TITLE
Complete stage page

### ISSUE THREAD

**Issue by lburkett** [ASUKanbosalCapstone/Kanbosal#82]
### Problem

Currently we are storing fully completed cards in stage index 3, or the "complete" stage, however we do not have a current view for it.
### Solution

We can either make a new page for this, or perhaps just make a new template for the complete cards to be displayed in detail. If we go with the new template, we can just check the returned object from '/getDetail' to see if it is the complete stage and if it is display that template instead of the normal detail view template. The returned object for the complete stage will simply contain a progress and cards key and nothing else like the other stages.

If we decide to go with a completely new page almost all of the assets for it can just be copy pasted together from the existing detail page.

As for the layout and look of the complete table, I was thinking we just keep with the theme we have going on with the detail pages. The complete table would occupy all 3 columns and we would keep the same card/modal setup that is currently in place for the detail page. Any thoughts as to how this should be accomplished?

**Comment by mjyi2** [comment]
I heard you and Allen discussing the complications with how the cards transitioned between boards, has that been resolved? 

What direction were we moving towards with this?

**Comment by allenduy** [comment]
I'm thinking the overview page itself should show the completed cards, whichever method seems most appropriate (maybe expand using bootstrap's [collapse](http://getbootstrap.com/javascript/#collapse) right below the progress bars, I was also thinking of adding the edit form like this as well). It won't need any kind of sortable or editing, just display the list of completed cards without detail, and probably a modal (without editable class, and other things) just to view the contents of the card. A shortcut to the link can be directly inline with the title like `[Example Title ... []]` where `[]` would be the little icon. Similar to admin page's deactivated users section.

Thoughts on this?

[edit] maybe the expansion can show more detail, as in the edit grant form and completed items.

**Comment by mjyi2** [comment]
That sounds pretty good. But I'm just worried if there is a ton of cards for a grant, having all of those pop up in the column might get messy?

**Comment by allenduy** [comment]
They wouldn't be showing as cards, since we won't need to drag them around, so they would at most show one line per 'card'. Also, the column would be hidden until it gets expanded when a user wants to see it.

[edit] Maybe using this: [Bootstrap's List Groups](http://getbootstrap.com/components/#list-group)

**Comment by lburkett** [comment]
So if all the cards are going to be view-able from the complete columns in every stage I'm not sure if this issue is even necessary anymore. If anyone wanted to see a completed card they could just look in their own table. In the case of the PIs, they would look at the ASU board and the complete column there would have a history of everything fully completed.

I'm working on some changes to utilize the locks and if cards are locked for a stage, they would have a special icon indicated as such. I could keep going with this idea and make it so when all the stages have been locked it has another icon indicating it has completed all the stages. How about something like this over seeing all the cards again?

**Comment by allenduy** [comment]
Ahh, that's sounds much cleaner, haha. Also, I'm not fully understanding your last question.
[edit] you wont have to check if they're all locked. Once the card is confirmed to be in the last stage, that's where you can add the icon/label.

**Comment by mjyi2** [comment]
Okay that makes sense.

So would there be a special icon after each stage has been completed? Or just at the end when it's been fully completed?

**Comment by lburkett** [comment]
Oh just meant the implementation I had suggested. I will have some changes up in a branch later that will make more sense as to what I am doing.

Jay, as for now there isn't a ton of main features to look at. Allen was talking about taking the card locks to the next stage by removing the ability to drag them in the tables. Perhaps he can write up a new issue as I wasn't entirely understanding how he meant to implement this and you can take this on?

**Comment by allenduy** [comment]
Basically if lock # 4 (index 3) is true, then show icon.

**Comment by allenduy** [comment]
Oh you mean jquery ui sortable locks. I'll update issue #31 with some resources.
[edit] updated issue 31

**Comment by lburkett** [comment]
Closing this issue since we are not going to implement this suggestion.
