### ISSUE TITLE
Delete card removed top-most card of column.

### ISSUE THREAD

**Issue by allenduy** [ASUKanbosalCapstone/Kanbosal#95]

**Comment by lburkett** [comment]
I have a feeling the jquery selector that specifies which card it is deleting is off or selecting the wrong card. Is it occurring regularly?

**Comment by allenduy** [comment]
Yeah, I made a new card on the one starter grant on aws, tried deleting the card, which was at the bottom, and the top one went away. Noticed it didn't go away, tried again, next top one left, then I realized it, hahah. Tried it with another one in the middle, and top one also removed.
